apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: hse-llm-project
spec:
  type: LoadBalancer
  selector:
    app: coredns-external
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
